feat: log

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -21,8 +21,9 @@ jobs:
         run: npm install
 
       - name: Lint code
-        run: npm run lint
-        run: echo "Linting completed"
+        run: npm run lint \
+          || { echo 'Linting errors found'; exit 1; }
+
 
       
    
